[settings]
experimental = true

[tools]
node = "latest"
"npm:markdownlint" = "latest"
"npm:prettier" = "latest"
direnv = "latest"
kubie = "latest"
awscli = "latest"
ruby = "latest"
k3d = "5.6.0"
xh = "latest"
